import { BookOpenCheck, CalendarDays, ChevronRight, ClipboardCheck, MessageCircle, TrendingUp, UsersRound } from "lucide-react";

import { PlatformShell } from "@/components/platform-shell";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";

const students = [
  ["Alice Martins", "AM", "78%", "Em dia"], ["Bernardo Lima", "BL", "64%", "Acompanhar"], ["Clara Nunes", "CN", "82%", "Em dia"], ["Davi Ribeiro", "DR", "71%", "Em dia"], ["Elisa Souza", "ES", "55%", "Apoio"],
];

export default function ClassesPage() {
  return <PlatformShell activeHref="/turmas">
    <section className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#17767a]">Acompanhamento</p><h1 className="mt-1 font-serif text-4xl text-[#173657] sm:text-5xl">5º ano A</h1><p className="mt-3 text-sm text-[#6f7c75]">24 alunos · Turno matutino · Ano letivo 2026</p></div><div className="flex gap-2"><Button variant="outline" className="rounded-xl bg-white"><MessageCircle className="size-4" />Comunicado</Button><Button className="rounded-xl bg-[#0b407e]"><ClipboardCheck className="size-4" />Registrar encontro</Button></div></section>
    <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[UsersRound, "24", "Alunos", "2 novos este ano"], [BookOpenCheck, "04", "Aula atual", "Fenômenos urbanos"], [TrendingUp, "71%", "Progresso médio", "+8% neste mês"], [CalendarDays, "92%", "Participação", "Últimos 30 dias"]].map(([Icon, value, label, detail]) => { const ItemIcon = Icon as typeof UsersRound; return <Card key={String(label)} className="border-[#dfe6df] bg-white py-0"><CardContent className="p-5"><div className="flex items-center justify-between"><div className="grid size-9 place-items-center rounded-xl bg-[#edf4ee] text-[#26747a]"><ItemIcon className="size-[18px]" /></div><Badge variant="secondary" className="bg-[#f4f6f2] text-[9px]">Atualizado</Badge></div><strong className="mt-5 block text-3xl font-semibold text-[#173657]">{String(value)}</strong><p className="mt-1 text-xs font-semibold text-[#50655c]">{String(label)}</p><p className="mt-1 text-[10px] text-[#89948e]">{String(detail)}</p></CardContent></Card>; })}</div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_0.75fr]">
      <Card className="border-[#dfe6df] bg-white py-0"><CardHeader className="border-b border-[#edf0ec] px-6 py-5"><div className="flex items-center justify-between"><CardTitle className="font-serif text-2xl text-[#173657]">Alunos</CardTitle><Button variant="ghost" size="sm" className="rounded-xl">Ver todos</Button></div></CardHeader><CardContent className="p-0"><div className="divide-y divide-[#edf0ec]">{students.map(([name, initials, progress, status]) => <div key={name} className="grid grid-cols-[1fr_100px_92px_24px] items-center gap-3 px-6 py-4"><div className="flex items-center gap-3"><Avatar className="size-9"><AvatarFallback className="bg-[#e7f1ed] text-[10px] font-bold text-[#287378]">{initials}</AvatarFallback></Avatar><div><p className="text-sm font-semibold text-[#2f485b]">{name}</p><p className="text-[10px] text-[#87928c]">Último acesso hoje</p></div></div><div><p className="mb-1 text-[10px] text-[#7a8780]">{progress}</p><Progress value={Number(progress.replace("%", ""))} className="h-1.5 [&>div]:bg-[#49a2a2]" /></div><Badge className={`justify-center border-0 text-[9px] ${status === "Em dia" ? "bg-[#eaf3dd] text-[#557629]" : status === "Apoio" ? "bg-[#fff0e8] text-[#a55333]" : "bg-[#edf3f6] text-[#44697e]"}`}>{status}</Badge><ChevronRight className="size-4 text-[#9aa39e]" /></div>)}</div></CardContent></Card>
      <div className="space-y-5"><Card className="border-[#dfe6df] bg-[#08366f] py-0 text-white"><CardContent className="p-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#78d4d2]">Próximo encontro</p><h3 className="mt-3 font-serif text-2xl">Fenômenos urbanos</h3><p className="mt-2 text-xs leading-relaxed text-white/62">A cidade como organismo vivo: alimentação, consumo e transformação do ambiente.</p><div className="mt-6 flex items-end justify-between"><div><p className="text-[10px] text-white/45">Preparação</p><strong className="text-xl">68%</strong></div><Button size="sm" className="rounded-xl bg-white text-[#08366f] hover:bg-white/90">Continuar</Button></div><Progress value={68} className="mt-3 h-1.5 bg-white/15 [&>div]:bg-[#a8d62e]" /></CardContent></Card><Card className="border-[#dfe6df] bg-white py-0"><CardContent className="p-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#76837c]">Pontos de atenção</p><div className="mt-4 space-y-4">{["5 alunos ainda não retomaram a Aula 3", "2 famílias enviaram novas observações", "Atividade impressa pendente"].map((item, index) => <div key={item} className="flex gap-3"><span className={`mt-1 size-2 rounded-full ${index === 0 ? "bg-[#e29161]" : "bg-[#55a6a4]"}`} /><p className="text-xs leading-relaxed text-[#65736c]">{item}</p></div>)}</div></CardContent></Card></div>
    </div>
  </PlatformShell>;
}
