import { CalendarDays, CheckCircle2, MapPin, Plus } from "lucide-react";
import { PlatformShell } from "@/components/platform-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

export default function AgendaPage() {
  const events = [["08:00", "5º ano A", "Fenômenos urbanos", "Sala 05", "aula"], ["10:15", "5º ano B", "Cidadania", "Sala 06", "aula"], ["14:00", "Encontro pedagógico", "Curadoria do percurso", "Sala dos professores", "equipe"], ["17:30", "Atendimento às famílias", "Conversas agendadas", "Coordenação", "familia"]];
  return <PlatformShell activeHref="/agenda"><section className="flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#17767a]">Organização</p><h1 className="mt-1 font-serif text-4xl text-[#173657] sm:text-5xl">Agenda</h1><p className="mt-3 text-sm text-[#6f7c75]">Quinta-feira, 28 de agosto de 2026</p></div><Button className="rounded-xl bg-[#0b407e]"><Plus className="size-4" />Novo compromisso</Button></section><div className="mt-7 grid gap-6 xl:grid-cols-[1.4fr_0.6fr]"><Card className="border-[#dfe6df] bg-white py-0"><CardContent className="p-6"><div className="space-y-2">{events.map(([time, title, subtitle, place, type]) => <div key={`${time}-${title}`} className="grid gap-4 rounded-2xl p-4 transition hover:bg-[#f6f8f4] sm:grid-cols-[64px_1fr_auto]"><div><p className="text-sm font-bold text-[#21445e]">{time}</p><p className="mt-1 text-[9px] text-[#8b9690]">60 min</p></div><div className="border-l-2 border-[#64aaa8] pl-4"><div className="flex items-center gap-2"><p className="text-sm font-semibold text-[#314c60]">{title}</p><Badge variant="secondary" className="text-[8px]">{type}</Badge></div><p className="mt-1 text-xs text-[#738079]">{subtitle}</p><p className="mt-2 flex items-center gap-1 text-[10px] text-[#929b96]"><MapPin className="size-3" />{place}</p></div><Button variant="outline" size="sm" className="self-center rounded-xl">Abrir</Button></div>)}</div></CardContent></Card><aside className="space-y-5"><Card className="border-0 bg-[#08366f] py-0 text-white"><CardContent className="p-6"><CalendarDays className="size-5 text-[#78d4d2]" /><p className="mt-5 text-xs text-white/55">Semana 35</p><strong className="mt-1 block font-serif text-3xl">8 encontros</strong><p className="mt-2 text-xs text-white/55">2 planejamentos · 1 atendimento</p></CardContent></Card><Card className="border-[#dfe6df] bg-white py-0"><CardContent className="p-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#75817b]">Preparação do dia</p><div className="mt-4 space-y-3">{["Materiais da Aula 4 separados", "Atividade impressa revisada", "Observações da turma registradas"].map((item, index) => <p key={item} className="flex items-start gap-2 text-xs leading-relaxed text-[#617068]"><CheckCircle2 className={`mt-0.5 size-4 shrink-0 ${index < 2 ? "text-[#73a438]" : "text-[#b1bab5]"}`} />{item}</p>)}</div></CardContent></Card></aside></div></PlatformShell>;
}
