import { ArrowRight, Bell, BookOpenText, CalendarDays, HeartHandshake, MessageCircle, Sparkles } from "lucide-react";

import { PlatformShell } from "@/components/platform-shell";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";

export default function FamilyPage() {
  return <PlatformShell activeHref="/familia" roleLabel="Família · Clara"><section className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#17767a]">Olá, família da Clara</p><h1 className="mt-1 font-serif text-4xl text-[#173657] sm:text-5xl">Acompanhar sem invadir</h1><p className="mt-3 max-w-2xl text-sm leading-relaxed text-[#6f7c75]">Uma visão simples do percurso, com ideias para conversar e aprender também fora da tela.</p></div><Button variant="outline" className="self-start rounded-xl bg-white"><MessageCircle className="size-4" />Falar com o colégio</Button></section>
    <div className="mt-7 grid gap-6 xl:grid-cols-[1.45fr_0.75fr]">
      <div className="space-y-5"><Card className="overflow-hidden border-0 bg-[#08366f] py-0 text-white"><CardContent className="relative grid gap-7 p-7 sm:grid-cols-[1fr_190px]"><div className="absolute -right-12 -bottom-28 size-64 rounded-full bg-[#a8d62e]" /><div className="relative"><div className="flex items-center gap-3"><Avatar className="size-12 border-2 border-white/20"><AvatarFallback className="bg-[#d9edeb] font-bold text-[#17676d]">CN</AvatarFallback></Avatar><div><p className="text-lg font-semibold">Clara Nunes</p><p className="text-xs text-white/52">5º ano A · Matutino</p></div></div><p className="mt-7 text-xs font-semibold uppercase tracking-[0.15em] text-[#7dd7d6]">Aprendendo agora</p><h2 className="mt-2 font-serif text-3xl">Fenômenos urbanos</h2><p className="mt-3 max-w-lg text-sm leading-relaxed text-white/65">Cidades, alimentação, consumo consciente e os impactos das escolhas humanas.</p><Button className="mt-6 rounded-xl bg-white text-[#08366f] hover:bg-white/90">Conhecer a aula<ArrowRight className="size-4" /></Button></div><div className="relative self-end rounded-2xl border border-white/12 bg-white/8 p-5"><p className="text-xs text-white/55">Percurso da Clara</p><strong className="mt-2 block text-3xl">82%</strong><Progress value={82} className="mt-3 h-1.5 bg-white/15 [&>div]:bg-[#a8d62e]" /><p className="mt-3 text-[10px] text-white/48">Em dia com a turma</p></div></CardContent></Card>
        <div className="grid gap-4 md:grid-cols-2"><Card className="border-[#dfe6df] bg-white py-0"><CardContent className="p-6"><div className="grid size-10 place-items-center rounded-xl bg-[#e9f2df] text-[#5f812d]"><HeartHandshake className="size-[18px]" /></div><p className="mt-5 text-[10px] font-semibold uppercase tracking-[0.14em] text-[#76837c]">Conversa em família</p><h3 className="mt-1 font-serif text-xl text-[#173657]">O que mudou no nosso bairro?</h3><p className="mt-3 text-xs leading-relaxed text-[#6f7c75]">Escolham um lugar conhecido e conversem sobre como ele era antes, como é hoje e o que gostariam para o futuro.</p><Button variant="link" className="mt-3 h-auto p-0 text-xs text-[#176f78]">Guardar ideia →</Button></CardContent></Card><Card className="border-[#dfe6df] bg-white py-0"><CardContent className="p-6"><div className="grid size-10 place-items-center rounded-xl bg-[#e6f1f3] text-[#397489]"><BookOpenText className="size-[18px]" /></div><p className="mt-5 text-[10px] font-semibold uppercase tracking-[0.14em] text-[#76837c]">Para retomar</p><h3 className="mt-1 font-serif text-xl text-[#173657]">Desenvolvimento da vida</h3><p className="mt-3 text-xs leading-relaxed text-[#6f7c75]">Clara marcou a leitura sobre sistema respiratório para revisar. O caderno está disponível para consulta.</p><Button variant="link" className="mt-3 h-auto p-0 text-xs text-[#176f78]">Abrir material →</Button></CardContent></Card></div>
      </div>
      <aside className="space-y-5"><Card className="border-[#dfe6df] bg-white py-0"><CardContent className="p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#75817b]">Próximos dias</p><h3 className="mt-1 font-serif text-2xl text-[#173657]">Agenda</h3></div><CalendarDays className="size-5 text-[#4b8f90]" /></div><div className="mt-5 space-y-5">{[["29 AGO", "Atividade de observação", "Levar caderno"], ["02 SET", "Encontro com famílias", "18h30 · Colégio"], ["05 SET", "Mostra do percurso", "5º ano"]].map(([date, title, detail]) => <div key={date} className="flex gap-3"><div className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#eff4ed] text-center text-[9px] font-bold leading-tight text-[#456459]">{date}</div><div><p className="text-sm font-semibold text-[#324b5d]">{title}</p><p className="mt-0.5 text-[10px] text-[#87918c]">{detail}</p></div></div>)}</div></CardContent></Card><Card className="border-0 bg-[#edf4df] py-0"><CardContent className="p-6"><Sparkles className="size-5 text-[#57792a]" /><h3 className="mt-4 font-serif text-xl text-[#29485a]">Menos tela, mais experiência</h3><p className="mt-2 text-xs leading-relaxed text-[#65736a]">As propostas para casa priorizam observação, conversa, leitura e atividades concretas. A plataforma é o ponto de apoio, não o destino.</p></CardContent></Card><Card className="border-[#dfe6df] bg-white py-0"><CardContent className="p-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#75817b]">Avisos</p><div className="mt-4 rounded-xl bg-[#f5f7f3] p-4"><div className="flex items-start gap-3"><Bell className="mt-0.5 size-4 text-[#4c8588]" /><div><p className="text-xs font-semibold text-[#385469]">Mostra do percurso Kinesis</p><p className="mt-1 text-[10px] leading-relaxed text-[#7b8781]">As famílias estão convidadas para acompanhar as produções da turma.</p></div></div></div></CardContent></Card></aside>
    </div></PlatformShell>;
}
