import { ArrowUpRight, BookOpenCheck, CheckCircle2, Clock3, FileSearch, ShieldCheck, TrendingUp, UsersRound } from "lucide-react";

import { PlatformShell } from "@/components/platform-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";

export default function LeadershipPage() {
  const metrics = [[UsersRound, "148", "Usuários ativos", "+12 este mês"], [BookOpenCheck, "06", "Aulas publicadas", "5º ano completo"], [FileSearch, "18", "Itens em curadoria", "7 aguardam revisão"], [TrendingUp, "84%", "Adoção docente", "+9% em 30 dias"]];
  return <PlatformShell activeHref="/diretoria" roleLabel="Diretora"><section className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#17767a]">Visão institucional</p><h1 className="mt-1 font-serif text-4xl text-[#173657] sm:text-5xl">Diretoria pedagógica</h1><p className="mt-3 max-w-2xl text-sm leading-relaxed text-[#6f7c75]">Acompanhe a saúde do acervo, a participação da comunidade e a evolução do conhecimento produzido pelo colégio.</p></div><Button className="self-start rounded-xl bg-[#0b407e]"><ShieldCheck className="size-4" />Gerenciar acessos</Button></section>
    <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([Icon, value, label, detail]) => { const ItemIcon = Icon as typeof UsersRound; return <Card key={String(label)} className="border-[#dfe6df] bg-white py-0"><CardContent className="p-5"><div className="grid size-9 place-items-center rounded-xl bg-[#edf4ee] text-[#26747a]"><ItemIcon className="size-[18px]" /></div><strong className="mt-5 block text-3xl font-semibold text-[#173657]">{String(value)}</strong><p className="mt-1 text-xs font-semibold text-[#50655c]">{String(label)}</p><p className="mt-1 text-[10px] text-[#89948e]">{String(detail)}</p></CardContent></Card>; })}</div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.25fr_0.75fr]"><Card className="border-[#dfe6df] bg-white py-0"><CardHeader className="border-b border-[#edf0ec] px-6 py-5"><div className="flex items-center justify-between"><CardTitle className="font-serif text-2xl text-[#173657]">Saúde do percurso</CardTitle><Badge variant="secondary" className="bg-[#eaf3dd] text-[#557629]">Estável</Badge></div></CardHeader><CardContent className="p-6"><div className="space-y-6">{[["Conteúdo-base organizado", 100, "6 de 6 aulas"], ["Materiais com audiência definida", 100, "12 de 12 materiais"], ["Contribuições pedagógicas", 58, "7 de 12 esperadas"], ["Revisão de direitos autorais", 72, "13 de 18 itens"]].map(([label, value, detail]) => <div key={String(label)}><div className="mb-2 flex items-center justify-between"><p className="text-xs font-semibold text-[#3c5668]">{String(label)}</p><span className="text-[10px] text-[#7c8982]">{String(detail)}</span></div><Progress value={Number(value)} className="h-2 [&>div]:bg-[#49a2a2]" /></div>)}</div></CardContent></Card><Card className="border-[#dfe6df] bg-white py-0"><CardHeader className="px-6 pt-6 pb-3"><CardTitle className="font-serif text-2xl text-[#173657]">Fila de curadoria</CardTitle></CardHeader><CardContent className="px-6 pb-6"><div className="space-y-4">{[["Vídeo sobre urbanização", "Sugerido por Marina", "Novo"], ["Mapa interativo de migrações", "Sugerido por Ana", "Revisar"], ["Atividade sobre consumo", "Editado por Carlos", "Direitos"]].map(([title, author, status]) => <div key={title} className="rounded-xl border border-[#e6eae6] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-[#385267]">{title}</p><p className="mt-1 text-[10px] text-[#87928c]">{author}</p></div><Badge variant="secondary" className="text-[9px]">{status}</Badge></div><Button variant="ghost" size="sm" className="mt-2 -ml-3 h-7 text-[10px] text-[#176f78]">Analisar<ArrowUpRight className="size-3" /></Button></div>)}</div></CardContent></Card></div>
    <div className="mt-6 grid gap-4 md:grid-cols-3">{[[CheckCircle2, "Segurança", "Todas as tabelas expostas estão protegidas por RLS."], [Clock3, "Continuidade", "O acervo preserva atualizações e decisões pedagógicas."], [ShieldCheck, "Curadoria", "Conteúdo novo só é publicado depois da revisão humana."]].map(([Icon, title, body]) => { const ItemIcon = Icon as typeof ShieldCheck; return <Card key={String(title)} className="border-[#dfe6df] bg-[#f9fbf7] py-0"><CardContent className="p-5"><ItemIcon className="size-5 text-[#43878a]" /><h3 className="mt-4 text-sm font-semibold text-[#365066]">{String(title)}</h3><p className="mt-2 text-xs leading-relaxed text-[#748078]">{String(body)}</p></CardContent></Card>; })}</div>
  </PlatformShell>;
}
